### ISSUE TITLE
Clarification on API Endpoint

### ISSUE THREAD

**Issue by AdonousTech** [bitclout/backend#65]
Hello,

I would like to clarify the policy on accessing the API endpoint. I noticed a few comments from the core devs recommending "running your own node". Obviously it is faster and cheaper to get a proof-of-concept running and even production level apps, if one could rely on the API endpoint, indefinitely.

1. What is the risk of building apps that rely on the API endpoint? 
2. Why is it not recommended? 
3. Are there long term plans to lockdown or stop supporting the API endpoint?
4.  If the answer to 3 is "No", what is the change management strategy? 

As you know, recent changes to API endpoints have broken apps. For example, the change to the send-bitclout endpoint to add a CAPTCHA challenge broke apps running in production. If there are problems with bots, why not simply require an API Key? We could easily pass that in an Auth header, and that would allow the core devs to monitor API traffic.

Please let me know, as the uncertainty affects all development plans.

Thank you.

**Comment by maebeam** [comment]
The risk of building a production app against our hosted version of the API is that it is subject to any number of things: breaking changes, downtime, maintenance, captchas, etc. It's not recommended because running your own API promotes the decentralization of BitClout and gives you full control over the release cycle. I can't promise that we will or won't continue to support any of these endpoints.

While you are totally welcome to build the first version of your project against our API, we would like to see someone in the community offer a versioned BitClout API as a service for projects that don't want to be responsible for running nodes. I've considered doing this myself but don't have enough time at the moment. 

Hope this helps clarify how we're approaching this issue.

**Comment by AdonousTech** [comment]
OK, thanks for the info @maebeam. I appreciate it!

**Comment by tijno** [comment]
> OK, thanks for the info @maebeam. I appreciate it!

hey hit me up you can use my node for api requests - will be adding versioned api endpoints soon as maebeam outlined

**Comment by AdonousTech** [comment]
That's awesome @tijno ! Where can I find more info? Thanks! 😊

**Comment by tijno** [comment]
DM me in bitclout @tijn
